name: cars_app_flutter
description: Une application Flutter CRUD pour voitures avec Firebase et Wireframe
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  firebase_auth: ^6.1.2

  # Images
  image_picker: ^1.2.1

  # Local storage
  shared_preferences: ^2.1.0

  # UI & icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/banner.jpg
    - assets/car1.jpg
    - assets/car2.jpg
    - assets/car3.jpg
    - assets/car4.jpg
    - assets/suv.jpg
    - assets/berline.jpg
    - assets/sportive.jpg
    - assets/electrique.jpg
